// Command fixture dumps the main quotes database into a SQL insert script used
// as the clone-of-main test fixture (internal/store/storetest/testdata). Run
// `make fixture` to refresh it; the main DB is (re)seeded idempotently first,
// so the command works on a clean checkout.
package main

import (
	"database/sql"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/lavantien/quotes-manager/internal/seed"
	"github.com/lavantien/quotes-manager/internal/store"
)

func main() {
	dbPath := flag.String("db", "database/quotes.db", "source SQLite database (seeded if empty)")
	outPath := flag.String("out", "internal/store/storetest/testdata/quotes_fixture.sql", "output SQL fixture path")
	flag.Parse()
	if err := run(*dbPath, *outPath); err != nil {
		log.Fatalf("fixture: %v", err)
	}
	log.Printf("wrote %s", *outPath)
}

// run seeds the source DB idempotently, dumps every data table in a stable
// order, and writes the insert script to outPath.
func run(dbPath, outPath string) error {
	st, err := store.Open(dbPath)
	if err != nil {
		return err
	}
	defer st.Close()
	if err := seed.EnsureSeeded(st.DB()); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("-- Clone of the main quotes database; generated by cmd/fixture; do not edit.\n")
	b.WriteString("-- Loaded by internal/store/storetest.CloneFixture into a temp DB per test.\n")
	for _, t := range tables {
		if err := dumpTable(&b, st.DB(), t); err != nil {
			return fmt.Errorf("dump %s: %w", t.name, err)
		}
	}
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

// tables lists every data table in dependency order with the columns and
// deterministic ordering the fixture must reproduce.
var tables = []table{
	{"quotes", []string{"id", "sutta_id", "citation", "body_md", "body_text", "line_count", "char_count", "sources"}, "id"},
	{"collections", []string{"id", "name"}, "id"},
	{"collection_items", []string{"collection_id", "quote_id", "position"}, "collection_id, position"},
	{"categories", []string{"id", "name"}, "id"},
	{"category_items", []string{"category_id", "quote_id"}, "category_id, quote_id"},
}

type table struct {
	name    string
	columns []string
	orderBy string
}

func dumpTable(b *strings.Builder, db *sql.DB, t table) error {
	q := fmt.Sprintf("SELECT %s FROM %s ORDER BY %s", strings.Join(t.columns, ", "), t.name, t.orderBy)
	rs, err := db.Query(q)
	if err != nil {
		return err
	}
	defer rs.Close()
	cols := strings.Join(t.columns, ", ")
	for rs.Next() {
		vals := make([]any, len(t.columns))
		ptrs := make([]any, len(t.columns))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rs.Scan(ptrs...); err != nil {
			return err
		}
		fmt.Fprintf(b, "INSERT INTO %s (%s) VALUES (%s);\n", t.name, cols, formatValues(vals))
	}
	return rs.Err()
}

func formatValues(vals []any) string {
	parts := make([]string, len(vals))
	for i, v := range vals {
		parts[i] = formatValue(v)
	}
	return strings.Join(parts, ", ")
}

func formatValue(v any) string {
	switch x := v.(type) {
	case nil:
		return "NULL"
	case int64:
		return fmt.Sprintf("%d", x)
	case float64:
		return fmt.Sprintf("%g", x)
	case string:
		return sqlString(x)
	case []byte:
		return sqlString(string(x))
	default:
		return "NULL"
	}
}

// sqlString emits a single-quoted SQL string literal with embedded quotes
// doubled, matching the escaping internal/quote uses for seed.sql.
func sqlString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}
