package quote

import (
	"fmt"
	"strings"
)

// sqlString quotes a string for SQLite, doubling embedded single quotes.
func sqlString(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// schemaSQL recreates the quotes table from scratch (idempotent re-runs).
const schemaSQL = `DROP TABLE IF EXISTS quotes;
CREATE TABLE quotes (
    id          INTEGER PRIMARY KEY,     -- shortest-first rank
    sutta_id    TEXT    NOT NULL,        -- canonical id, e.g. "MN 22"
    citation    TEXT    NOT NULL,        -- full kept citation
    body_md     TEXT    NOT NULL,        -- canonical italicized format
    body_text   TEXT    NOT NULL,        -- plain passages joined by newlines
    line_count  INTEGER NOT NULL,        -- passage line count
    char_count  INTEGER NOT NULL,        -- rune count of passages (sort key)
    sources     TEXT    NOT NULL         -- ';'-joined dump files
);
CREATE INDEX idx_quotes_char_count ON quotes(char_count);
CREATE INDEX idx_quotes_sutta_id   ON quotes(sutta_id);
`

// RenderSeedSQL emits the full seed.sql for the given (already sorted) quotes.
func RenderSeedSQL(qs []*Quote) string {
	var b strings.Builder
	b.WriteString("-- Auto-generated by cmd/extract; do not edit by hand.\n")
	b.WriteString(schemaSQL)
	b.WriteByte('\n')
	for i, q := range qs {
		fmt.Fprintf(&b,
			"INSERT INTO quotes (id, sutta_id, citation, body_md, body_text, line_count, char_count, sources) VALUES (%d, %s, %s, %s, %s, %d, %d, %s);\n",
			i+1,
			sqlString(q.SuttaID),
			sqlString(q.Citation),
			sqlString(q.BodyMD()),
			sqlString(q.BodyText()),
			q.LineCount(),
			q.CharCount(),
			sqlString(strings.Join(q.Sources, ";")),
		)
	}
	return b.String()
}
